
GET http://localhost:3000/

###

POST http://localhost:3000/auth
Content-Type: application/json

{
    "username":"Rorschach",
    "password":"crimebuster"
}

###

POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYzNDc1NThhMTU1ZWQyZDdhMzgzN2RjOCIsInVzZXJuYW1lIjoia2lobm8iLCJlbWFpbCI6InN0aXN0eWxlMTNAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkMjA1QURpL2RjTE9uQ3lJOUhLZzdFZXRFcXdFVkZickRSUDdocjRHTzhXNlQ3VE1JeENzWjYiLCJhZG1pbiI6dHJ1ZSwiY3JlYXRlZEF0IjoiMjAyMi0xMC0xM1QwMDowMjoxOC43OTBaIiwidXBkYXRlZEF0IjoiMjAyMi0xMC0xM1QwMDowMjoxOC43OTBaIiwiX192IjowfSwiaWF0IjoxNjY1NjE5MzQxLCJleHAiOjE2NjU2MjI5NDF9.Vy40ded2v1WwbM0O82qU5xpiF9jS-LFD3M6AvmphEbw

{
    "title": "post title",
    "text": "post text"
}

###

GET http://localhost:3000/posts

###

PATCH http://localhost:3000/posts/634608b1c3d855e00bcc5cf0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYzNDYwNzExNWUxOWIzYTY1NmNiNWIxMyIsInVzZXJuYW1lIjoia2lobm8iLCJlbWFpbCI6InN0aXN0eWxlMTNAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAka2FLMlQvSURUU3VLb2tlVU5sLkVLT3h0NEdlSXlvWUlGZ0pzYURKN1hUZWlxZHIzOTVmbHkiLCJhZG1pbiI6dHJ1ZSwiY3JlYXRlZEF0IjoiMjAyMi0xMC0xMlQwMDoxNToxNC4xNjlaIiwidXBkYXRlZEF0IjoiMjAyMi0xMC0xMlQwMDoxNToxNC4xNjlaIiwiX192IjowfSwiaWF0IjoxNjY1NTMzNzE3LCJleHAiOjE2NjU1MzczMTd9.FoyeO1vTAGVnPoNrpQ7QMH-s-yjDjofaxvp88GAPwnA

{
    "title": "Updated post title",
    "text": "Updated post text"
}

###

GET http://localhost:3000/posts/63471d1eb2c189dd021d5503

###

DELETE http://localhost:3000/posts/634608b1c3d855e00bcc5cf0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYzNDYwNzExNWUxOWIzYTY1NmNiNWIxMyIsInVzZXJuYW1lIjoia2lobm8iLCJlbWFpbCI6InN0aXN0eWxlMTNAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAka2FLMlQvSURUU3VLb2tlVU5sLkVLT3h0NEdlSXlvWUlGZ0pzYURKN1hUZWlxZHIzOTVmbHkiLCJhZG1pbiI6dHJ1ZSwiY3JlYXRlZEF0IjoiMjAyMi0xMC0xMlQwMDoxNToxNC4xNjlaIiwidXBkYXRlZEF0IjoiMjAyMi0xMC0xMlQwMDoxNToxNC4xNjlaIiwiX192IjowfSwiaWF0IjoxNjY1NTMzNzE3LCJleHAiOjE2NjU1MzczMTd9.FoyeO1vTAGVnPoNrpQ7QMH-s-yjDjofaxvp88GAPwnA

###

GET http://localhost:3000/posts/634758813ccb0a569f3bf410/comments

###

GET http://localhost:3000/posts/63471aa4d38697316985cc65/comments/63471aa4d38697316985cc66

###

POST http://localhost:3000/posts/63475c46eae244dd51ed539b/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYzNDc1YzQ2ZWFlMjQ0ZGQ1MWVkNTM5YSIsInVzZXJuYW1lIjoiUm9yc2NoYWNoIiwiZW1haWwiOiJ1dG9waWF6b2xhcmlzQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJFVjTk90eG9jMDFPTXJCMEdDOWU1VWU1RlFOUnNVS01tb0l1S0hLRXJ4dWw2cFQ0dXplc0dPIiwiYWRtaW4iOmZhbHNlLCJjcmVhdGVkQXQiOiIyMDIyLTEwLTEzVDAwOjMxOjAyLjczNFoiLCJ1cGRhdGVkQXQiOiIyMDIyLTEwLTEzVDAwOjMxOjAyLjczNFoiLCJfX3YiOjB9LCJpYXQiOjE2NjU2MjEwNjYsImV4cCI6MTY2NTYyNDY2Nn0.3migTWMEYy1tAnVRFitlokVYfV1hVQ_RK2WEn16EkvQ

{
    "text": "test comment"
}

###

DELETE http://localhost:3000/posts/63471efd71e495d0581f2d0e/comments/63471f1c71e495d0581f2d1a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYzNDcxYWE0ZDM4Njk3MzE2OTg1Y2M2MyIsInVzZXJuYW1lIjoia2lobm8iLCJlbWFpbCI6InN0aXN0eWxlMTNAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkOW5HS043bmZwQ3FaMnpHd1FSaklaZTYydDZNUU1rRy5OQzRwVTJyLzk4Yk82N09MaGhnRjIiLCJhZG1pbiI6dHJ1ZSwiY3JlYXRlZEF0IjoiMjAyMi0xMC0xMlQxOTo1MTowMC45NjNaIiwidXBkYXRlZEF0IjoiMjAyMi0xMC0xMlQxOTo1MTowMC45NjNaIiwiX192IjowfSwiaWF0IjoxNjY1NjA0NDc2LCJleHAiOjE2NjU2MDgwNzZ9.5OzthkVF66tVefKaW0A1coSRnXT9sNUaNsff8_TU_8Q

###

GET http://localhost:3000/users


###

GET http://localhost:3000/users/634720f8fadc29d8af1f3b48

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "testUser",
    "email": "test@email.com",
    "password": "password"
}

###

PATCH http://localhost:3000/users/6347521c2d418debfd45b038
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYzNDc1MWVhMmQ0MThkZWJmZDQ1YjAyZCIsInVzZXJuYW1lIjoia2lobm8iLCJlbWFpbCI6InN0aXN0eWxlMTNAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkcDRUSE9mQkRHRFlLTzZLY1l6SU5tdWZnMWZGVE90cDFZdlVVaEhUMEtoVTlENFNldUZKb3EiLCJhZG1pbiI6dHJ1ZSwiY3JlYXRlZEF0IjoiMjAyMi0xMC0xMlQyMzo0Njo1MC44NjRaIiwidXBkYXRlZEF0IjoiMjAyMi0xMC0xMlQyMzo0Njo1MC44NjRaIiwiX192IjowfSwiaWF0IjoxNjY1NjE4NTAxLCJleHAiOjE2NjU2MjIxMDF9.yKG5NiGzVMWSLBXX95ItYbNrUsoG8JZRng3Mj_9sph8

{
    "username":"betterUsername"
}

###

DELETE http://localhost:3000/users/6347521c2d418debfd45b038
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYzNDc1MWVhMmQ0MThkZWJmZDQ1YjAyZCIsInVzZXJuYW1lIjoia2lobm8iLCJlbWFpbCI6InN0aXN0eWxlMTNAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkcDRUSE9mQkRHRFlLTzZLY1l6SU5tdWZnMWZGVE90cDFZdlVVaEhUMEtoVTlENFNldUZKb3EiLCJhZG1pbiI6dHJ1ZSwiY3JlYXRlZEF0IjoiMjAyMi0xMC0xMlQyMzo0Njo1MC44NjRaIiwidXBkYXRlZEF0IjoiMjAyMi0xMC0xMlQyMzo0Njo1MC44NjRaIiwiX192IjowfSwiaWF0IjoxNjY1NjE4NTAxLCJleHAiOjE2NjU2MjIxMDF9.yKG5NiGzVMWSLBXX95ItYbNrUsoG8JZRng3Mj_9sph8
