
GET http://localhost:3000/

###

POST http://localhost:3000/auth
Content-Type: application/json

{
    "username":"kihno",
    "password":"blackapple"
}

###

POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYzNDYwNzExNWUxOWIzYTY1NmNiNWIxMyIsInVzZXJuYW1lIjoia2lobm8iLCJlbWFpbCI6InN0aXN0eWxlMTNAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAka2FLMlQvSURUU3VLb2tlVU5sLkVLT3h0NEdlSXlvWUlGZ0pzYURKN1hUZWlxZHIzOTVmbHkiLCJhZG1pbiI6dHJ1ZSwiY3JlYXRlZEF0IjoiMjAyMi0xMC0xMlQwMDoxNToxNC4xNjlaIiwidXBkYXRlZEF0IjoiMjAyMi0xMC0xMlQwMDoxNToxNC4xNjlaIiwiX192IjowfSwiaWF0IjoxNjY1NTMzNzE3LCJleHAiOjE2NjU1MzczMTd9.FoyeO1vTAGVnPoNrpQ7QMH-s-yjDjofaxvp88GAPwnA

{
    "title": "post title",
    "text": "post text"
}

###

GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYzNDYwNzExNWUxOWIzYTY1NmNiNWIxMyIsInVzZXJuYW1lIjoia2lobm8iLCJlbWFpbCI6InN0aXN0eWxlMTNAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAka2FLMlQvSURUU3VLb2tlVU5sLkVLT3h0NEdlSXlvWUlGZ0pzYURKN1hUZWlxZHIzOTVmbHkiLCJhZG1pbiI6dHJ1ZSwiY3JlYXRlZEF0IjoiMjAyMi0xMC0xMlQwMDoxNToxNC4xNjlaIiwidXBkYXRlZEF0IjoiMjAyMi0xMC0xMlQwMDoxNToxNC4xNjlaIiwiX192IjowfSwiaWF0IjoxNjY1NTMzNzE3LCJleHAiOjE2NjU1MzczMTd9.FoyeO1vTAGVnPoNrpQ7QMH-s-yjDjofaxvp88GAPwnA

###

PATCH http://localhost:3000/posts/634607c96a0752a83da553f4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYzNDYwNzExNWUxOWIzYTY1NmNiNWIxMyIsInVzZXJuYW1lIjoia2lobm8iLCJlbWFpbCI6InN0aXN0eWxlMTNAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAka2FLMlQvSURUU3VLb2tlVU5sLkVLT3h0NEdlSXlvWUlGZ0pzYURKN1hUZWlxZHIzOTVmbHkiLCJhZG1pbiI6dHJ1ZSwiY3JlYXRlZEF0IjoiMjAyMi0xMC0xMlQwMDoxNToxNC4xNjlaIiwidXBkYXRlZEF0IjoiMjAyMi0xMC0xMlQwMDoxNToxNC4xNjlaIiwiX192IjowfSwiaWF0IjoxNjY1NTMzNzE3LCJleHAiOjE2NjU1MzczMTd9.FoyeO1vTAGVnPoNrpQ7QMH-s-yjDjofaxvp88GAPwnA

{
    "title": "Updated post title",
    "text": "Updated post text"
}

###

GET http://localhost:3000/posts/634607c96a0752a83da553f4